# Module 4 Lab 2

In [1]:
import pandas as pd
originaldf = pd.read_csv('allbacks.csv')
df = originaldf

In [2]:
df.shape

(15, 5)

In [3]:
df.head()

   rownames  volume  area  weight cover
0         1     885   382     800    hb
1         2    1016   468     950    hb
2         3    1125   387    1050    hb
3         4     239   371     350    hb
4         5     701   371     750    hb

In [4]:
df.describe()

        rownames       volume        area       weight
count  15.000000    15.000000   15.000000    15.000000
mean    8.000000   845.266667  182.800000   706.666667
std     4.472136   339.879909  203.586837   268.837887
min     1.000000   239.000000    0.000000   250.000000
25%     4.500000   618.000000    0.000000   512.500000
50%     8.000000   929.000000    0.000000   725.000000
75%    11.500000  1025.000000  376.500000   950.000000
max    15.000000  1492.000000  468.000000  1075.000000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  15 non-null     int64
 1   volume    15 non-null     int64
 2   area      15 non-null     int64
 3   weight    15 non-null     int64
 4   cover     15 non-null     str
dtypes: int64(4), str(1)
memory usage: 762.0 bytes

Area "min" and Q1, Q2 are 0 but info says non-null?
The data set in the book does not have null values.
The heatmap says no null. HMMMM

In [6]:
df.sort_values("area")
df.head(16)

    rownames  volume  area  weight cover
0          1     885   382     800    hb
1          2    1016   468     950    hb
2          3    1125   387    1050    hb
3          4     239   371     350    hb
4          5     701   371     750    hb
5          6     641   367     600    hb
6          7    1228   396    1075    hb
7          8     412     0     250    pb
8          9     953     0     700    pb
9         10     929     0     650    pb
10        11    1492     0     975    pb
11        12     419     0     350    pb
12        13    1010     0     950    pb
13        14     595     0     425    pb
14        15    1034     0     725    pb

In [7]:
print(df["area"].mean())
print(df["area"].median())

182.8
0.0

This data set does not the data set listed in the book. I edited the missing data to match that of the book and named it nonull_allbacks.

In [8]:
import pandas as pd
nonulldf = pd.read_csv('nonull_allbacks.csv')
df = nonulldf

In [9]:
df.tail()

    rownames  volume  area  weight cover
10        11    1492   403     975    pb
11        12     419   213     350    pb
12        13    1010   432     950    pb
13        14     595   262     425    pb
14        15    1034   380     725    pb

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  15 non-null     int64
 1   volume    15 non-null     int64
 2   area      15 non-null     int64
 3   weight    15 non-null     int64
 4   cover     15 non-null     str
dtypes: int64(4), str(1)
memory usage: 762.0 bytes

In [11]:
df.describe()

        rownames       volume        area       weight
count  15.000000    15.000000   15.000000    15.000000
mean    8.000000   845.266667  352.666667   706.666667
std     4.472136   339.879909   70.707311   268.837887
min     1.000000   239.000000  213.000000   250.000000
25%     4.500000   618.000000  300.500000   512.500000
50%     8.000000   929.000000  371.000000   725.000000
75%    11.500000  1025.000000  391.500000   950.000000
max    15.000000  1492.000000  468.000000  1075.000000

In [12]:
# mean and median weight
print(df["weight"].mean())
print(df["weight"].median())

706.6666666666666
725.0

In [13]:
# median cover type
# print(df["cover"].median()) - THIS DOES NOT WORK

# Median calculation Method 1
print(df["cover"].value_counts())

cover
pb    8
hb    7
Name: count, dtype: int64

There are 7 pb and 8 hp, if you were to take away one pb and one hb until you are in the middle (median) you would be left with the one pb. Therefore median is pb

In [14]:
# Median calculation Method 2: count and check value at half of count.
print(df["cover"].count())

15

In [15]:
# If 15 values, median is halfway, therefore row 8. 
df.iloc[8]["cover"]

'pb'

In [16]:
# Median calculation Method 3: Write an if else loop
# sort_values (cover).
# count values
# if count == 1, print (print(df.iat[1, 4])
# else delete row(1) and row(count)
        count values

IndentationError: unexpected indent (3255510435.py, line 6)

In [ ]:
df.groupby("cover")["weight"].mean()

In [ ]:
# Test by hand on calculator and here
print(df["weight"].sum())
print(df["weight"].count())

In [ ]:
# Mean of all books by hand
10600/15

Corrrect,same answer as print(df["weight"].mean())


The average weight of all the books is is 706.67 grams.
The average weight of the hardcover books is 796.43 grams
The average weight of the softcover books is 628.13 grams

The average weight of the paperbacks is less than that of the hardcover. The average weight of all the books is between the average weight of the cover types. This gives an indication that there are not

In [ ]:
# average hb - average all average
796.43-706.67

In [ ]:
# average all average - average pb
706.67-628.13

The average weight of all books is a little closer to the softcover average weight indicating that there are slightly more softcover books. If there were many more softcover books, the average of all books would be closer to the average of the softcover weight (and vice versa), meaning the all books mean would be skewed in the direction for which there are more books of a particular cover type.