# Module 6 LAB 3

In [1]:
#Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [2]:
#REBUILD Lab 2 Table Here
#Connect to SQL3 database
con = sqlite3.connect("store.db")




con.commit() #Do this after every addition!

In [3]:
#Create cursor to execute SQL communications
cur = con.cursor()

In [4]:
# Drop table before creating so no duplicates
cur.execute("""
DROP TABLE IF EXISTS 'customers';""")

In [5]:
#Create a table - with at least id, name, city, and one numeric column and 8 rows
cur.execute("""
CREATE TABLE IF NOT EXISTS 'customers' (
'ID' INTEGER PRIMARY KEY AUTOINCREMENT,
'Name' TEXT,
'City' TEXT,
'NumInHousehold' INTEGER);""")

In [6]:
#Insert values into customer table
cur.execute("""
    INSERT INTO customers (Name, City, NumInHousehold) VALUES
        ("Andrew", "Anchorage", 1),
        ("Betty", "Boston", 2),
        ("Charles", "Chatanooga", 3),
        ("Darla", "Detroit", 4),
        ("Elliot", "El Paso", 1),
        ("Frances", "Frisco", 2),
        ("Gerald", "Galveston", 3),
        ("Henrietta", "Houston", 4);""")

In [7]:
#Check input
pd.read_sql("SELECT * FROM customers", con)

   ID       Name        City  NumInHousehold
0   1     Andrew   Anchorage               1
1   2      Betty      Boston               2
2   3    Charles  Chatanooga               3
3   4      Darla     Detroit               4
4   5     Elliot     El Paso               1
5   6    Frances      Frisco               2
6   7     Gerald   Galveston               3
7   8  Henrietta     Houston               4

In [8]:
#Query all data for customers having households greater than 1 person (SELECT WHERE)
cur.execute("""
    SELECT *
    FROM customers
    WHERE NumInHousehold > 1;
    """)
#Fetch all matching rows
rows = cur.fetchall()

# Print the results
print("Customers with more than 1 person in the household:")
for row in rows:
    print(row)

Customers with more than 1 person in the household:
(2, 'Betty', 'Boston', 2)
(3, 'Charles', 'Chatanooga', 3)
(4, 'Darla', 'Detroit', 4)
(6, 'Frances', 'Frisco', 2)
(7, 'Gerald', 'Galveston', 3)
(8, 'Henrietta', 'Houston', 4)

In [9]:
#Query all data for customers having households greater than 1 person and order by name
cur.execute("""
    SELECT *
    FROM customers
    WHERE NumInHousehold > 1
    ORDER BY Name;
    """)

#Fetch all matching rows
rows = cur.fetchall()

# Print the results
print("Customers with more than 1 person in the household, ordered by name:")
for row in rows:
    print(row)

Customers with more than 1 person in the household, ordered by name:
(2, 'Betty', 'Boston', 2)
(3, 'Charles', 'Chatanooga', 3)
(4, 'Darla', 'Detroit', 4)
(6, 'Frances', 'Frisco', 2)
(7, 'Gerald', 'Galveston', 3)
(8, 'Henrietta', 'Houston', 4)

In [10]:
#Query the customer database for customers living in cities containing "San", (LIKE San Diego and San Francisco)

cur.execute("""
    SELECT *
    FROM customers
    WHERE City LIKE '%on%';
    """)

#Fetch all matching rows
rows = cur.fetchall()

# Print the results
print("Customers living in cities containing '%on':")
for row in rows:
    print(row)

Customers living in cities containing '%on':
(2, 'Betty', 'Boston', 2)
(7, 'Gerald', 'Galveston', 3)
(8, 'Henrietta', 'Houston', 4)

In [11]:
#Labeled Chart: Show all data for customers having households greater than 1 person, ordered by name.

#Input query
pd.read_sql("SELECT * FROM customers WHERE NumInHousehold > 1 ORDER BY Name", con)

   ID       Name        City  NumInHousehold
0   2      Betty      Boston               2
1   3    Charles  Chatanooga               3
2   4      Darla     Detroit               4
3   6    Frances      Frisco               2
4   7     Gerald   Galveston               3
5   8  Henrietta     Houston               4

https://github.com/acamend/cs82a-portfolio